org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.enableJetifier=true
# Safe release build
android.injected.testOnly=false
# warning show
org.gradle.warning.mode=all
# Enable ANGLE (OpenGL over Vulkan) to prevent PowerVR / IMG GPU crashes.......
android.enableAngleSupport=true

# ================== Add For 16KB ================================
# Native library compression settings for 16KB alignment
android.native.buildOutputs=true
android.enableParallelForNativeBuild=true

# Build optimization
org.gradle.parallel=true
org.gradle.caching=true
